name: Build InCom Opérations APK

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      # 1. تحميل المشروع
      - name: Checkout
        uses: actions/checkout@v4


      # 2. إعداد Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'


      # 3. إعداد Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3


      # 4. إعطاء صلاحية Gradle
      - name: Make Gradle executable
        run: |
          chmod +x gradlew


      # 5. بناء APK
      - name: Build APK
        run: |
          ./gradlew assembleDebug


      # 6. رفع APK كملف قابل للتحميل
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: InCom-Operations-APK
          path: app/build/outputs/apk/debug/app-debug.apk
